"""
Django settings for car_sharing project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# BASE_DIR указывает на корневую папку нашего проекта.
BASE_DIR = Path(__file__).resolve().parent.parent

# Секретный ключ для шифрования данных.
SECRET_KEY = 'django-insecure-g=k_#e^(bn(5w%#rzq$1(2pnmml^&basedhnak*+e4y6_we+bq'

# Режим отладки для разработки, в будущем должен быть FALSE
DEBUG = True

ALLOWED_HOSTS = []


# Определение установленных приложений из списка готовых решений Django и самого проекта

INSTALLED_APPS = [
    'django.contrib.admin',         # Админ-панель
    'django.contrib.auth',          # Аутентификация
    'django.contrib.contenttypes',  # Типы контента
    'django.contrib.sessions',      # Сессии
    'django.contrib.messages',      # Сообщения
    'django.contrib.staticfiles',   # Статические файлы
    'tempus_dominus',               # Виджеты для выбора даты и времени
    'rentapp'                       # Само приложение аренды из проекта
]

# Промежуточные слои обработки запросов. Здесь указаны все middlewares, которые будут выполняться на каждом запросе.
# Нужны для изменения логики ответов приложений на запросы
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Указывает на основной файл конфигурации URL'ов проекта.
ROOT_URLCONF = 'car_sharing.urls'

# Настройка шаблонов для HTML файлов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # Движок шаблонов. По умолчанию применяется встроенный движок django.template.backends.django.DjangoTemplates
        'DIRS': [], # Определяет список каталогов, где движок шаблонов будет искать файлы шаблонов. По умолчанию пустой список
        'APP_DIRS': True, # Указывает, будет ли движок шаблонов искать шаблоны внутри папок приложений в папке templates.
        'OPTIONS': { # Доп. параметры
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Указывает на файл конфигурации WSGI, который используется для развертывания проекта.
WSGI_APPLICATION = 'car_sharing.wsgi.application'


# Настройка базы данных
# Здесь указано какая база данных будет использоваться (SQLite самый простой в использовании вариант)
# И путь к файлу БД
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Настройки валидаторов паролей. Они помогают делать пароли более безопасными.

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # Минимальная  длина пароля
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # Простой валидатор (цифра, буква и тд)
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Настройки интернационализации (переводы, временные зоны и т.д.)

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#  Настройки для статических файлов (CSS, JavaScript, изображения).

STATIC_URL = 'static/'

# Настройки для перенаправления после входа и выхода из аккаунта.
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Настройки для поля с первичным ключом по умолчанию (чтобы первичный ключ по дефолту был Long).
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
